FROM docker.io/node:lts-alpine

ENV HOST=127.0.0.1
ENV PORT=3000

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN addgroup --system nexus-api && \
          adduser --system -G nexus-api nexus-api
COPY /dist/apps/backend/nexus-api nexus-api
RUN chown -R nexus-api:nexus-api .

CMD [ "node", "nexus-api/main.js" ]