# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  provider "google" {
    # credentials = file("novel-nexus-monorepo-e9ba23c5fbe5.json")
    project     = "novel-nexus-monorepo"
    region      = "us-central1"
  }
