# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Development

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
          version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "pnpm"
    - uses: nrwl/nx-set-shas@v3

    - name: Build All App
      run: pnpm all:build
    - name: Unit Test All App
      run: pnpm all:test
