name: Development

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build-and-test:
    name: Build & Cache Dependency
    runs-on: ubuntu-latest
    environment: Development

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
          version: 8
    - name: Install NX
      uses: nrwl/nx-set-shas@v3
      with:
        main-branch-name: "${{ vars.BRANCH_NAME }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: |
        pnpm i --frozen-lockfile
    - name: Check Lint Affected
      run: |
        pnpm nx affected -t lint --parallel=3
    - name: Check Test Affected
      run: |
        pnpm nx affected -t test --parallel=3 --configuration=ci
    - name: Build Affected
      run: |
        pnpm nx affected -t build --parallel=3
    
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    environment: Development
    needs: build-and-test

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
          version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

    - name: Deploy Application
      run: |
        echo "Deploy to GCP"
