name: Development

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v2
      with:
          version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "pnpm"
    - uses: nrwl/nx-set-shas@v3
      with:
        main-branch-name: 'development'

    - name: Build All App
      run: pnpm all:build
    - name: Unit Test All App
      run: pnpm all:test
