name: Staging

on:
  pull_request:
    branches: [ "staging" ]

jobs:
  Install:
    name: Install & Cache Dependency
    runs-on: ubuntu-latest
    environment: Staging

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v2
      with:
          version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "pnpm"
    - uses: nrwl/nx-set-shas@v3
      with:
        main-branch-name: "${{ vars.BRANCH_NAME }}"
    - run: pnpm i --frozen-lockfile
    
  Test:
    name: Testing Affected
    runs-on: ubuntu-latest
    environment: Staging
    needs: Install
    
    steps:
    - run: pnpm exec nx format:check
    - run: pnpm exec nx affected -t lint --parallel=3
    - run: pnpm exec nx affected -t test --parallel=3 --configuration=ci

  Build:
    name: Build Affected to Staging Server
    runs-on: ubuntu-latest
    environment: Staging
    needs: Test
    
    steps:
    - run: pnpm exec nx affected -t build --parallel=3
